// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0
// source: copyfrom.go

package dbmodel

import (
	"context"
)

// iteratorForInsertInitialBloggers implements pgx.CopyFromSource.
type iteratorForInsertInitialBloggers struct {
	rows                 []InsertInitialBloggersParams
	skippedFirstNextCall bool
}

func (r *iteratorForInsertInitialBloggers) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForInsertInitialBloggers) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].DatasetID,
		r.rows[0].Username,
		r.rows[0].UserID,
		r.rows[0].IsInitial,
	}, nil
}

func (r iteratorForInsertInitialBloggers) Err() error {
	return nil
}

func (q *Queries) InsertInitialBloggers(ctx context.Context, arg []InsertInitialBloggersParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"bloggers"}, []string{"dataset_id", "username", "user_id", "is_initial"}, &iteratorForInsertInitialBloggers{rows: arg})
}
