// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0
// source: query.sql

package dbmodel

import (
	"github.com/google/uuid"
	"time"
)

type SaveBotAccountsParams struct {
	Username  string     `json:"username"`
	SessionID string     `json:"session_id"`
	WorkProxy *string    `json:"work_proxy"`
	IsBlocked bool       `json:"is_blocked"`
	StartedAt *time.Time `json:"started_at"`
}

type SaveTargetUsersParams struct {
	DatasetID uuid.UUID `json:"dataset_id"`
	Username  string    `json:"username"`
	UserID    int64     `json:"user_id"`
}
