version: "3.9"

services:
  parser:
    image: 'ghcr.io/inst-api/parser:latest'
    restart: unless-stopped
    ports:
      - "9090:9090" # REST
      - "9091:9091" # GRPC
    volumes:
      - tmp_logs:/root/tmp
    networks:
      - postgres_ompnw


networks:
  postgres_ompnw:
    driver: bridge
    external: true

volumes:
  tmp_logs:
    name: parser_logs
    driver: local