version: "3.9"

services:
  parser:
    image: 'ghcr.io/inst-api/parser:latest'
    restart: unless-stopped
    ports:
      - "9090:9090" # REST
      - "9091:9091" # GRPC
    volumes:
      - ./tmp:/root/tmp
    networks:
      - poster_ompnw


networks:
  poster_ompnw:
    driver: bridge
    external: true