version: "3.9"

services:
  parser:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        CONFIG_MODE: local_docker
    restart: unless-stopped
    ports:
      - "9090:9090" # REST
    volumes:
      - tmp:/root/tmp
    networks:
      - postgres_ompnw

networks:
  postgres_ompnw:
    driver: bridge
    external: true

volumes:
  tmp:
    name: logs
    driver: local