version: "3.9"

services:
  parser:
    image: 'ghcr.io/inst-api/parser:latest'
    restart: unless-stopped
    ports:
      - "9090:9090" # REST
    #    healthcheck:
    #      test: ['CMD', 'curl', '-f', 'http://localhost:8000/live']
    #      interval: 1m
    #      timeout: 10s
    #      retries: 3
    #      start_period: 20s
    volumes:
      - ./tmp:/root/tmp
    networks:
      - poster_ompnw


networks:
  poster_ompnw:
    driver: bridge
    external: true